name: 🐛 Bug Report
description: Report a bug or issue with the portfolio
title: '[Bug]: '
labels: ['bug', 'needs-triage']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us reproduce and fix the issue.

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this hasn't been reported before
          required: true
        - label: I have read the [Contributing Guidelines](../../CONTRIBUTING.md)
          required: true
        - label: This bug is reproducible on the latest version
          required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Clear steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
      value: |
        1. 
        2. 
        3. 
        4.
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: Browser(s)
      description: Which browser(s) are you experiencing this issue on?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Mobile Safari (iOS)
        - Chrome Mobile (Android)
        - Other
    validations:
      required: true

  - type: input
    id: browser-version
    attributes:
      label: Browser Version
      description: What version of the browser are you using?
      placeholder: e.g. Chrome 118.0.5993.117

  - type: dropdown
    id: device-type
    attributes:
      label: Device Type
      description: What type of device are you using?
      options:
        - Desktop
        - Mobile
        - Tablet
    validations:
      required: true

  - type: input
    id: screen-resolution
    attributes:
      label: Screen Resolution
      description: What is your screen resolution?
      placeholder: e.g. 1920x1080, 375x667 (mobile)

  - type: dropdown
    id: bug-category
    attributes:
      label: Bug Category
      description: What type of bug is this?
      options:
        - UI/Visual Issue
        - Performance Issue
        - Accessibility Issue
        - Functionality Issue
        - Build/Deployment Issue
        - Content Issue
        - Internationalization Issue
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (Site is broken/unusable)
        - High (Major functionality affected)
        - Medium (Minor functionality affected)
        - Low (Cosmetic issue)
    validations:
      required: true

  - type: textarea
    id: console-errors
    attributes:
      label: Console Errors
      description: Any errors in the browser console?
      placeholder: |
        If applicable, paste any console errors here.
        You can find these in Developer Tools > Console.
      render: javascript

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: |
        If applicable, add screenshots to help explain your problem.
        You can drag and drop images here.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here

  - type: checkboxes
    id: accessibility-impact
    attributes:
      label: Accessibility Impact
      description: Does this bug affect accessibility?
      options:
        - label: This bug affects keyboard navigation
        - label: This bug affects screen reader users
        - label: This bug affects color contrast/visibility
        - label: This bug affects focus management
        - label: No accessibility impact

  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: If you've found a temporary workaround, please describe it here
