name: 📚 Documentation Issue
description: Report missing, unclear, or incorrect documentation
title: '[Docs]: '
labels: ['documentation', 'needs-triage']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! Clear, accurate documentation is essential for this academic portfolio project.

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this hasn't been reported before
          required: true
        - label: I have read the [Contributing Guidelines](../../CONTRIBUTING.md)
          required: true

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation issue is this?
      options:
        - Missing Documentation
        - Incorrect Information
        - Unclear Instructions
        - Outdated Information
        - Typo/Grammar Error
        - Broken Links
        - Code Examples Don't Work
        - Accessibility Documentation
        - Translation Issue
        - Other
    validations:
      required: true

  - type: textarea
    id: doc-location
    attributes:
      label: Documentation Location
      description: Where is this documentation issue located?
      placeholder: |
        Please specify:
        - File name (e.g., README.md, CONTRIBUTING.md)
        - Section/heading (e.g., "Getting Started" section)
        - URL (if applicable)
        - Line numbers (if specific)
    validations:
      required: true

  - type: textarea
    id: current-content
    attributes:
      label: Current Content
      description: What does the current documentation say? Quote the problematic section.
      placeholder: |
        Copy and paste the current text that needs to be fixed.
        If it's missing documentation, write "Missing" here.

  - type: textarea
    id: expected-content
    attributes:
      label: Expected/Suggested Content
      description: What should the documentation say instead?
      placeholder: |
        Provide the corrected text or describe what information should be included.
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: How does this documentation issue affect users?
      placeholder: |
        Describe the impact:
        - Are users getting confused?
        - Are instructions not working?
        - Is important information missing?
    validations:
      required: true

  - type: dropdown
    id: audience
    attributes:
      label: Target Audience
      description: Who is primarily affected by this documentation issue?
      options:
        - New Contributors
        - Experienced Developers
        - End Users
        - Academic Community
        - All Users
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this documentation issue?
      options:
        - Critical (Prevents users from completing essential tasks)
        - High (Causes significant confusion or errors)
        - Medium (Minor confusion but workarounds exist)
        - Low (Cosmetic issue with minimal impact)
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce (if applicable)
      description: If this involves instructions that don't work, provide steps to reproduce the issue
      placeholder: |
        1. Go to documentation section...
        2. Follow the instructions...
        3. Encounter the problem...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Add any other context about the documentation issue here.
        Screenshots, links to related documentation, or examples would be helpful.

  - type: checkboxes
    id: fix-offer
    attributes:
      label: Can you help fix this?
      description: Are you willing to help improve the documentation?
      options:
        - label: I can submit a pull request to fix this
        - label: I can provide the corrected content
        - label: I can help review proposed changes
        - label: I need someone else to fix this
