name: WASM Build

on:
  push:
    branches: [ main ]
    paths:
      - 'rust/perf_tools/**'
      - '.github/workflows/wasm-build.yml'
  workflow_dispatch:

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install wasm-pack
        run: cargo install wasm-pack --force
      - name: Build
        working-directory: rust/perf_tools
        run: wasm-pack build --target web --out-dir ../../public/wasm
      - name: List artifacts
        run: ls -lh public/wasm || true
